# Generated by Django 5.2.6 on 2025-10-03 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_position_alter_workplace_options_and_more"),
        ("employees", "0002_employeeimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "ordering": ["-hire_date"],
                "verbose_name": "Профиль сотрудника",
                "verbose_name_plural": "Профили сотрудников",
            },
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Биография"),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="hire_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата приёма на работу"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="company.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="workplace",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="company.workplace",
                verbose_name="Рабочее место",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Мужской"), ("Female", "Женский")],
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
