# Generated by Django 5.2.6 on 2025-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_position_alter_workplace_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="table_number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер стола"),
        ),
    ]
