# Generated by Django 5.2.6 on 2025-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
    ]
