# Generated by Django 5.2.6 on 2025-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employeeprofile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="is_watcher",
            field=models.BooleanField(default=False, verbose_name="Смотритель"),
        ),
    ]
