# Generated by Django 5.2.6 on 2025-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название должности"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Например: backend-developer",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "ordering": ["table_number"],
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
        migrations.RenameField(
            model_name="workplace",
            old_name="desk_number",
            new_name="table_number",
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="employee",
        ),
    ]
