services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: FrameworkDjango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azsxdc1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    command: >
      /wait-for-it.sh db:5432 -- sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      POSTGRES_DB: FrameworkDjango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azsxdc1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "db", "-p", "5432", "-U", "postgres" ]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: