# Generated by Django 5.2.6 on 2025-09-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="employee_gallery/", verbose_name="Изображение"
                    ),
                ),
                (
                    "order_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядковый номер"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="employees.employeeprofile",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение сотрудника",
                "verbose_name_plural": "Галерея сотрудника",
                "ordering": ["order_number"],
            },
        ),
    ]
